name: Build Cookie Monster EXE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Mingw-w64 Toolchain
      run: |
        sudo apt update
        sudo apt install -y mingw-w64

    - name: Build EXE (cookie-graber)
      run: |
        x86_64-w64-mingw32-gcc cookie-graber.c -o cookie-graber_x64.exe -lshlwapi -lcrypt32
        ls -l

    - name: Upload Compiled EXE Artifact
      uses: actions/upload-artifact@v4
      with:
        name: cookie-graber-exe
        path: cookie-graber_x64.exe
