name: Build Cookie Monster BOF

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Mingw-w64 Toolchain
      run: |
        sudo apt update
        sudo apt install -y mingw-w64

    - name: Build BOF Object (.o)
      run: |
        x86_64-w64-mingw32-gcc -c cookie-monster-bof.c -o cookie-monster-bof.x64.o
        ls -l

    - name: Upload BOF Artifact
      uses: actions/upload-artifact@v4
      with:
        name: cookie-monster-bof
        path: cookie-monster-bof.x64.o
